### ISSUE TITLE
Data issue - Typo in one of the Giant Robots podcast show notes?

### ISSUE THREAD

**Issue by boddhisattva** [thoughtbot/podcasts#16]
Dear Reader,

I think I found a typo in one of the Giant Robots podcast show notes on [Prolificness](http://giantrobots.fm/121) . I think the words `Guest-Ben` are additional. Please let me know if I'm missing something and also if this is not the right place to discuss such `data` related issues.

Thanks.

**Comment by cpytel** [comment]
Thanks. We no longer use this app for hosting our shows. We use http://simplecast.fm

I've forwarded your not to our producer.

**Comment by boddhisattva** [comment]
@cpytel Thanks for letting me know about SimpleCast. I have updated the app README in [this PR](https://github.com/thoughtbot/podcasts/pull/17) for the reference of users in the future.
